#!/bin/bash
USERID=$(id -u)
echo "UserID is $USERID"

R="\e[31m"
G="\e[32m"
CHECK_ROOT(){
if [ $USERID -ne 0 ]
then
   echo "Please run the script with root privileges"
   exit 1
fi

}
VALIDATE (){
    if [ $1 -ne 0 ]
    then 
        echo -e "$2 is $R Failed $N"
    else
        echo -e "$2 is $G Success $N"
    fi        
}

CHECK_ROOT


for package in $@ # $@ refers to all arguements passed to it
do
     #echo $package
     dnf list installed $package
     if [ $? -ne 0 ]
     then
        echo "$package is not installed going to install"
        dnf install $package -y
        VALIDATE $? "Installing $package"      
     else
        echo "$package is already installed"
    fi 
done
