#!/bin/bash
SOURCE_DIR=/home/ec2-user/logs

if [ -d ${SOURCE_DIR} ]
then 
    echo "${SOURCE_DIR} Exists"
else
    echo "${SOURCE_DIR} does not exists"
fi

FILES=$(find $SOURCE_DIR  -name "*.log" -mtime +17)
echo $FILES

while IFS= read line 
do 
echo "Deleting line : $line"
done <<< $FILES

